package com.example.version1.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.version1.Model.LentInformation;

import com.example.version1.greendao.LentInformationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lentInformationDaoConfig;

    private final LentInformationDao lentInformationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lentInformationDaoConfig = daoConfigMap.get(LentInformationDao.class).clone();
        lentInformationDaoConfig.initIdentityScope(type);

        lentInformationDao = new LentInformationDao(lentInformationDaoConfig, this);

        registerDao(LentInformation.class, lentInformationDao);
    }
    
    public void clear() {
        lentInformationDaoConfig.clearIdentityScope();
    }

    public LentInformationDao getLentInformationDao() {
        return lentInformationDao;
    }

}
