package com.example.version1.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.version1.greendao.MessageInformation;
import com.example.version1.greendao.LentInformation;

import com.example.version1.greendao.MessageInformationDao;
import com.example.version1.greendao.LentInformationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageInformationDaoConfig;
    private final DaoConfig lentInformationDaoConfig;

    private final MessageInformationDao messageInformationDao;
    private final LentInformationDao lentInformationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageInformationDaoConfig = daoConfigMap.get(MessageInformationDao.class).clone();
        messageInformationDaoConfig.initIdentityScope(type);

        lentInformationDaoConfig = daoConfigMap.get(LentInformationDao.class).clone();
        lentInformationDaoConfig.initIdentityScope(type);

        messageInformationDao = new MessageInformationDao(messageInformationDaoConfig, this);
        lentInformationDao = new LentInformationDao(lentInformationDaoConfig, this);

        registerDao(MessageInformation.class, messageInformationDao);
        registerDao(LentInformation.class, lentInformationDao);
    }
    
    public void clear() {
        messageInformationDaoConfig.clearIdentityScope();
        lentInformationDaoConfig.clearIdentityScope();
    }

    public MessageInformationDao getMessageInformationDao() {
        return messageInformationDao;
    }

    public LentInformationDao getLentInformationDao() {
        return lentInformationDao;
    }

}
