package com.example.version1.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.version1.greendao.MessageInformation;

import com.example.version1.greendao.MessageInformationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageInformationDaoConfig;

    private final MessageInformationDao messageInformationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageInformationDaoConfig = daoConfigMap.get(MessageInformationDao.class).clone();
        messageInformationDaoConfig.initIdentityScope(type);

        messageInformationDao = new MessageInformationDao(messageInformationDaoConfig, this);

        registerDao(MessageInformation.class, messageInformationDao);
    }
    
    public void clear() {
        messageInformationDaoConfig.clearIdentityScope();
    }

    public MessageInformationDao getMessageInformationDao() {
        return messageInformationDao;
    }

}
