package com.example.version1.Model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig lentInformationDaoConfig;
    private final DaoConfig messageInformationDaoConfig;

    private final LentInformationDao lentInformationDao;
    private final MessageInformationDao messageInformationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        lentInformationDaoConfig = daoConfigMap.get(LentInformationDao.class).clone();
        lentInformationDaoConfig.initIdentityScope(type);

        messageInformationDaoConfig = daoConfigMap.get(MessageInformationDao.class).clone();
        messageInformationDaoConfig.initIdentityScope(type);

        lentInformationDao = new LentInformationDao(lentInformationDaoConfig, this);
        messageInformationDao = new MessageInformationDao(messageInformationDaoConfig, this);

        registerDao(LentInformation.class, lentInformationDao);
        registerDao(MessageInformation.class, messageInformationDao);
    }
    
    public void clear() {
        lentInformationDaoConfig.clearIdentityScope();
        messageInformationDaoConfig.clearIdentityScope();
    }

    public LentInformationDao getLentInformationDao() {
        return lentInformationDao;
    }

    public MessageInformationDao getMessageInformationDao() {
        return messageInformationDao;
    }

}
